/**
 * Class description
 *
 * @author Dmytro Mytsko
 * @author Oleg Pasenchuk
 * @version 1.0.0
 */
public enum Services {
    Contract,
    Account,
    ContractResource,
    Products,
    TimesheetEntry,
    Timesheets,
    TimeReports,
    ExpenseEntry,
    User,
    FileUpload,
    ManagedServiceCase, 
    ManagedServiceCaseDelete,
    Invoices,
    Payments,
    ContractResourceRate,
    Email
}